# On merge into the `prod` branch, build the image and deploy to ECR.
# This is on `nypl-digital-dev` account.
name: Publish prod
on:
  push:
    branches:
      - production
env:
  AWS_ACCOUNT: "946183545209"
  AWS_REGION: us-east-1
  ENVIRONMENT: prod
permissions:
  id-token: write
  contents: read

jobs:
  publish_prod:
    name: Publish files to S3
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GithubActionsDeployerRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWSCLI package
        run: pip install --user awscli

      - name: Sync files to S3
        run: aws s3 sync ./ s3://production-nyclibraries.org --region=${{ env.AWS_REGION }} --delete --acl public-read --exclude ".git/*" --exclude ".*"
